name: KeepInventory
description: Keep your inventory upon death
author: StarTux
version: 0.1
api-version: '1.20'
website: https://cavetale.com
main: com.winthier.keepinventory.KeepInventoryPlugin
depend: [Connect]

commands:
  keepinventory:
    description: Turn keep inventory on or off
    permission: keepinventory.keepinventory
    usage: |-
      /<command> on|off

permissions:
  keepinventory.keepinventory:
    description: Use /keepinventory
    default: op
